language: objective-c
before_install:
- gem i cocoapods --no-ri --no-rdoc
- gem i xcpretty  --no-ri --no-rdoc
script:
- set -o pipefail && xcodebuild -workspace MGBoxKit.xcworkspace -scheme MGBoxKitTests -sdk iphonesimulator test | xcpretty -c
after_success: slather

